AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

Lint/UselessAssignment:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false
  
Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/Documentation:
  Enabled: false
